#!/bin/bash
set -e
THIS_FILE="$( basename "${BASH_SOURCE[0]:-${(%):-%x}}" )"
MAIN_DIR=/home/czy/nccl

# git clone
# export http_proxy=sys-proxy-rd-relay.byted.org:8118 https_proxy=sys-proxy-rd-relay.byted.org:8118 no_proxy=byted.org
# rm -rf $MAIN_DIR/msccl
# rm -rf $MAIN_DIR/npkit
# cd $MAIN_DIR && git clone https://github.com/yzh1703456/msccl-executor-nccl.git $MAIN_DIR/msccl
# mkdir -p $MAIN_DIR/npkit/
# cd $MAIN_DIR/npkit/ && git clone https://github.com/microsoft/NPKit.git
# cd $MAIN_DIR && git clone https://github.com/NVIDIA/nccl-tests 
# cd $MAIN_DIR && git clone https://github.com/wxzisk/TestXml_ring.git
# mkdir -p $MAIN_DIR/arnold/arnold_entrypoint/tools/
# mv -f $MAIN_DIR/TestXml_ring/MPIRUN $MAIN_DIR/arnold/arnold_entrypoint/tools/MPIRUN
chmod +x $MAIN_DIR/arnold/arnold_entrypoint/tools/MPIRUN

# # npkit debug
NPKIT_FLAGS_GPU_PREFIX="-DENABLE_NPKIT -DENABLE_NPKIT_EVENT_ALL_REDUCE_RING_ENTRY -DENABLE_NPKIT_EVENT_ALL_REDUCE_RING_EXIT -DENABLE_NPKIT_EVENT_ALL_REDUCE_TREE_UPDOWN_ENTRY -DENABLE_NPKIT_EVENT_ALL_REDUCE_TREE_UPDOWN_EXIT -DENABLE_NPKIT_EVENT_ALL_REDUCE_TREE_SPLIT_ENTRY -DENABLE_NPKIT_EVENT_ALL_REDUCE_TREE_SPLIT_EXIT -DENABLE_NPKIT_EVENT_COPY_SEND_ENTRY -DENABLE_NPKIT_EVENT_COPY_SEND_EXIT -DENABLE_NPKIT_EVENT_DIRECT_COPY_SEND_ENTRY -DENABLE_NPKIT_EVENT_DIRECT_COPY_SEND_EXIT -DENABLE_NPKIT_EVENT_DIRECT_RECV_ENTRY -DENABLE_NPKIT_EVENT_DIRECT_RECV_EXIT -DENABLE_NPKIT_EVENT_DIRECT_RECV_COPY_SEND_ENTRY -DENABLE_NPKIT_EVENT_DIRECT_RECV_COPY_SEND_EXIT -DENABLE_NPKIT_EVENT_DIRECT_RECV_REDUCE_COPY_SEND_ENTRY -DENABLE_NPKIT_EVENT_DIRECT_RECV_REDUCE_COPY_SEND_EXIT -DENABLE_NPKIT_EVENT_DIRECT_SEND_ENTRY -DENABLE_NPKIT_EVENT_DIRECT_SEND_EXIT -DENABLE_NPKIT_EVENT_DIRECT_SEND_FROM_OUTPUT_ENTRY -DENABLE_NPKIT_EVENT_DIRECT_SEND_FROM_OUTPUT_EXIT -DENABLE_NPKIT_EVENT_RECV_ENTRY -DENABLE_NPKIT_EVENT_RECV_EXIT -DENABLE_NPKIT_EVENT_RECV_COPY_SEND_ENTRY -DENABLE_NPKIT_EVENT_RECV_COPY_SEND_EXIT -DENABLE_NPKIT_EVENT_RECV_REDUCE_COPY_ENTRY -DENABLE_NPKIT_EVENT_RECV_REDUCE_COPY_EXIT -DENABLE_NPKIT_EVENT_RECV_REDUCE_COPY_SEND_ENTRY -DENABLE_NPKIT_EVENT_RECV_REDUCE_COPY_SEND_EXIT -DENABLE_NPKIT_EVENT_RECV_REDUCE_SEND_ENTRY -DENABLE_NPKIT_EVENT_RECV_REDUCE_SEND_EXIT -DENABLE_NPKIT_EVENT_SEND_ENTRY -DENABLE_NPKIT_EVENT_SEND_EXIT -DENABLE_NPKIT_EVENT_SEND_FROM_OUTPUT_ENTRY -DENABLE_NPKIT_EVENT_SEND_FROM_OUTPUT_EXIT -DENABLE_NPKIT_EVENT_PRIM_SIMPLE_WAIT_PEER_ENTRY -DENABLE_NPKIT_EVENT_PRIM_SIMPLE_WAIT_PEER_EXIT -DENABLE_NPKIT_EVENT_PRIM_SIMPLE_REDUCE_OR_COPY_MULTI_ENTRY -DENABLE_NPKIT_EVENT_PRIM_SIMPLE_REDUCE_OR_COPY_MULTI_EXIT -DENABLE_NPKIT_EVENT_PRIM_LL_WAIT_SEND_ENTRY -DENABLE_NPKIT_EVENT_PRIM_LL_WAIT_SEND_EXIT -DENABLE_NPKIT_EVENT_PRIM_LL_DATA_PROCESS_ENTRY -DENABLE_NPKIT_EVENT_PRIM_LL_DATA_PROCESS_EXIT -DENABLE_NPKIT_EVENT_PRIM_LL128_WAIT_SEND_ENTRY -DENABLE_NPKIT_EVENT_PRIM_LL128_WAIT_SEND_EXIT -DENABLE_NPKIT_EVENT_PRIM_LL128_DATA_PROCESS_ENTRY -DENABLE_NPKIT_EVENT_PRIM_LL128_DATA_PROCESS_EXIT -DENABLE_NPKIT_EVENT_NET_SEND_ENTRY -DENABLE_NPKIT_EVENT_NET_SEND_EXIT -DENABLE_NPKIT_EVENT_NET_RECV_ENTRY -DENABLE_NPKIT_EVENT_NET_RECV_EXIT -DENABLE_NPKIT_EVENT_TIME_SYNC_GPU -DENABLE_NPKIT_EVENT_TIME_SYNC_CPU -DENABLE_NPKIT_EVENT_ALL_REDUCE_RING_SEND_ENTRY -DENABLE_NPKIT_EVENT_ALL_REDUCE_RING_SEND_EXIT -DENABLE_NPKIT_EVENT_ALL_REDUCE_RING_RECV_REDUCE_SEND_ENTRY -DENABLE_NPKIT_EVENT_ALL_REDUCE_RING_RECV_REDUCE_SEND_EXIT -DENABLE_NPKIT_EVENT_ALL_REDUCE_RING_DIRECT_RECV_REDUCE_COPY_SEND_ENTRY -DENABLE_NPKIT_EVENT_ALL_REDUCE_RING_DIRECT_RECV_REDUCE_COPY_SEND_EXIT -DENABLE_NPKIT_EVENT_ALL_REDUCE_RING_DIRECT_RECV_COPY_SEND_ENTRY -DENABLE_NPKIT_EVENT_ALL_REDUCE_RING_DIRECT_RECV_COPY_SEND_EXIT -DENABLE_NPKIT_EVENT_ALL_REDUCE_RING_DIRECT_RECV_ENTRY -DENABLE_NPKIT_EVENT_ALL_REDUCE_RING_DIRECT_RECV_EXIT -DENABLE_NPKIT_EVENT_ALL_REDUCE_TREE_UPDOWN_REDUCE_ENTRY -DENABLE_NPKIT_EVENT_ALL_REDUCE_TREE_UPDOWN_REDUCE_EXIT -DENABLE_NPKIT_EVENT_ALL_REDUCE_TREE_UPDOWN_BROADCAST_ENTRY -DENABLE_NPKIT_EVENT_ALL_REDUCE_TREE_UPDOWN_BROADCAST_EXIT -DENABLE_NPKIT_EVENT_ALL_REDUCE_TREE_SPLIT_REDUCE_BROADCAST_ENTRY -DENABLE_NPKIT_EVENT_ALL_REDUCE_TREE_SPLIT_REDUCE_BROADCAST_EXIT -DENABLE_NPKIT_EVENT_ALL_REDUCE_TREE_SPLIT_REDUCE_ENTRY -DENABLE_NPKIT_EVENT_ALL_REDUCE_TREE_SPLIT_REDUCE_EXIT -DENABLE_NPKIT_EVENT_ALL_REDUCE_TREE_SPLIT_BROADCAST_ENTRY -DENABLE_NPKIT_EVENT_ALL_REDUCE_TREE_SPLIT_BROADCAST_EXIT -DENABLE_NPKIT_EVENT_SEND_RECV_LOCAL_COPY_ENTRY -DENABLE_NPKIT_EVENT_SEND_RECV_LOCAL_COPY_EXIT -DENABLE_NPKIT_EVENT_SEND_RECV_SEND_ENTRY -DENABLE_NPKIT_EVENT_SEND_RECV_SEND_EXIT -DENABLE_NPKIT_EVENT_SEND_RECV_RECV_ENTRY -DENABLE_NPKIT_EVENT_SEND_RECV_RECV_EXIT -DENABLE_NPKIT_PRIM_COLLECT_DATA_PROCESS_TIME -DENABLE_NPKIT_EVENT_MSCCL_GENERIC_OP_ENTRY -DENABLE_NPKIT_EVENT_MSCCL_GENERIC_OP_EXIT -DENABLE_NPKIT_EVENT_MSCCL_REDUCE_ENTRY -DENABLE_NPKIT_EVENT_MSCCL_REDUCE_EXIT"
# NPKIT_FLAGS_GPU_PREFIX="-DENABLE_NPKIT -DENABLE_NPKIT_EVENT_TIME_SYNC_CPU -DENABLE_NPKIT_EVENT_TIME_SYNC_GPU -DENABLE_NPKIT_EVENT_COPY_SEND_ENTRY -DENABLE_NPKIT_EVENT_COPY_SEND_EXIT -DENABLE_NPKIT_EVENT_DIRECT_COPY_SEND_ENTRY -DENABLE_NPKIT_EVENT_DIRECT_COPY_SEND_EXIT -DENABLE_NPKIT_EVENT_DIRECT_RECV_ENTRY -DENABLE_NPKIT_EVENT_DIRECT_RECV_EXIT -DENABLE_NPKIT_EVENT_DIRECT_RECV_COPY_SEND_ENTRY -DENABLE_NPKIT_EVENT_DIRECT_RECV_COPY_SEND_EXIT -DENABLE_NPKIT_EVENT_DIRECT_RECV_REDUCE_COPY_SEND_ENTRY -DENABLE_NPKIT_EVENT_DIRECT_RECV_REDUCE_COPY_SEND_EXIT -DENABLE_NPKIT_EVENT_DIRECT_SEND_ENTRY -DENABLE_NPKIT_EVENT_DIRECT_SEND_EXIT -DENABLE_NPKIT_EVENT_DIRECT_SEND_FROM_OUTPUT_ENTRY -DENABLE_NPKIT_EVENT_DIRECT_SEND_FROM_OUTPUT_EXIT -DENABLE_NPKIT_EVENT_RECV_ENTRY -DENABLE_NPKIT_EVENT_RECV_EXIT -DENABLE_NPKIT_EVENT_RECV_COPY_SEND_EXIT -DENABLE_NPKIT_EVENT_RECV_REDUCE_COPY_ENTRY -DENABLE_NPKIT_EVENT_RECV_REDUCE_COPY_EXIT -DENABLE_NPKIT_EVENT_RECV_REDUCE_COPY_SEND_ENTRY -DENABLE_NPKIT_EVENT_RECV_REDUCE_COPY_SEND_EXIT -DENABLE_NPKIT_EVENT_RECV_REDUCE_SEND_ENTRY -DENABLE_NPKIT_EVENT_RECV_REDUCE_SEND_EXIT -DENABLE_NPKIT_EVENT_SEND_ENTRY -DENABLE_NPKIT_EVENT_SEND_EXIT -DENABLE_NPKIT_EVENT_SEND_FROM_OUTPUT_ENTRY -DENABLE_NPKIT_EVENT_SEND_FROM_OUTPUT_EXIT"
export NPKIT_FLAGS=${NPKIT_FLAGS_GPU_PREFIX}
# # make
cd $MAIN_DIR/msccl && make -j src.build NPKIT_FLAGS="${NPKIT_FLAGS}" NVCC_GENCODE="-gencode=arch=compute_80,code=sm_80"
# cd $MAIN_DIR/nccl-tests && make clean && make -j MPI=1 MPI_HOME=/usr/lib/x86_64-linux-gnu/openmpi NPKIT_FLAGS="${NPKIT_FLAGS}" CUDA_HOME=/usr/local/cuda NCCL_HOME=$MAIN_DIR/msccl/build/
cd $MAIN_DIR/nccl-tests && make -j MPI=1 MPI_HOME=/usr/lib/x86_64-linux-gnu/openmpi NPKIT_FLAGS="${NPKIT_FLAGS}" CUDA_HOME=/usr/local/cuda NCCL_HOME=$MAIN_DIR/msccl/build/
# env
export NCCL_DEBUG_FILE=/dev/stderr
export LD_PRELOAD=$MAIN_DIR/msccl/build/lib/libnccl.so
export PATH=$PATH:$MAIN_DIR/arnold/arnold_entrypoint/tools/
mkdir -p $MAIN_DIR/npkit/dump
export NPKIT_DUMP_DIR=$MAIN_DIR/npkit/dump
export CUDA_VISIBLE_DEVICES=0,1,2,3
# export NCCL_TOPO_FILE=$MAIN_DIR/topo.xml


# echo "================== ring =================="
# for ((j=0;j<1;j++)) do
#     echo "===== Round $j ====="
#     ARGS=${*:-"-b 1M -e 2M -f 2"}
#     NCCL_ALGO=ring NCCL_PROTO=Simple mpirun -N 4 $MAIN_DIR/nccl-tests/build/all_gather_perf $ARGS -g 1 -n 2
#     echo "===== Done $j ====="
#     # if [[ $ARNOLD_ID != "0" ]]; then
#     #     echo Worker 0 finished? wait
#     #     sleep 1d
#     #     exit
#     # fi
# done

# echo "================== neogen ring 8*2 =================="
for ((j=0;j<1;j++)) do
    echo "===== Round $j ====="
    NPKIT_DUMP_DIR=$NPKIT_DUMP_DIR \
    mpirun -N 4 \
    -x LD_LIBRARY_PATH=$MAIN_DIR/msccl/build/lib:$LD_LIBRARY_PATH \
    -x NCCL_TOPO_FILE_PCIE=$MAIN_DIR/topo_mod.xml\
    -x NCCL_TOPO_DUMP_FILE_PCIE=$MAIN_DIR/topo_mod_pciedump.xml\
    -x NCCL_ALGO=MSCCL \
    -x NCCL_PROTO=Simple \
    -x NCCL_DEBUG=info \
    $MAIN_DIR/nccl-tests/build/all_gather_perf \
    -b 1M -e 1G -f 2 -g 1 -c 1 -n 1 -w 5 -G 0 -z 0 || true
    #    -x NCCL_TOPO_DUMP_FILE=$MAIN_DIR/topo.xml\
    #     -x NCCL_TOPO_DUMP_FILE=$MAIN_DIR/topo.xml\
    # -x NCCL_GRAPH_DUMP_FILE=$MAIN_DIR/graph.xml\
    # nsys profile --trace=cuda,nvtx,osrt --capture-range=nvtx --output=profile_report_ring4 \
    # --tag-output \
    # MSCCL_ALGO_DIR=$MAIN_DIR/TestXml_ring/Neogen_AG/4GPUs/ring4_1 \
    # NCCL_P2P_LEVEL=SYS \
    echo "===== Done $j ====="
    # if [[ $ARNOLD_ID != "0" ]]; then
    #     echo Worker 0 finished? wait
    #     sleep 1d
    #     exit
    # fi
done



MPIRUN /usr/bin/pkill -9 "$THIS_FILE" || true