#!/bin/bash
set -e
THIS_FILE="$( basename "${BASH_SOURCE[0]:-${(%):-%x}}" )"
MAIN_DIR=/data3/czy/nccl_origin

# git clone
# export http_proxy=sys-proxy-rd-relay.byted.org:8118 https_proxy=sys-proxy-rd-relay.byted.org:8118 no_proxy=byted.org
# rm -rf $MAIN_DIR/msccl
# rm -rf $MAIN_DIR/npkit
# cd $MAIN_DIR && git clone https://github.com/yzh1703456/msccl-executor-nccl.git $MAIN_DIR/msccl
# mkdir -p $MAIN_DIR/npkit/
# cd $MAIN_DIR/npkit/ && git clone https://github.com/microsoft/NPKit.git
# cd $MAIN_DIR && git clone https://github.com/NVIDIA/nccl-tests 
# cd $MAIN_DIR && git clone https://github.com/wxzisk/TestXml_ring.git
# mkdir -p $MAIN_DIR/arnold/arnold_entrypoint/tools/
# mv -f $MAIN_DIR/TestXml_ring/MPIRUN $MAIN_DIR/arnold/arnold_entrypoint/tools/MPIRUN
# chmod +x $MAIN_DIR/arnold/arnold_entrypoint/tools/MPIRUN

# # npkit debug
NPKIT_FLAGS_GPU_PREFIX="-DENABLE_NPKIT -DENABLE_NPKIT_EVENT_ALL_REDUCE_RING_ENTRY -DENABLE_NPKIT_EVENT_ALL_REDUCE_RING_EXIT -DENABLE_NPKIT_EVENT_ALL_REDUCE_TREE_UPDOWN_ENTRY -DENABLE_NPKIT_EVENT_ALL_REDUCE_TREE_UPDOWN_EXIT -DENABLE_NPKIT_EVENT_ALL_REDUCE_TREE_SPLIT_ENTRY -DENABLE_NPKIT_EVENT_ALL_REDUCE_TREE_SPLIT_EXIT -DENABLE_NPKIT_EVENT_COPY_SEND_ENTRY -DENABLE_NPKIT_EVENT_COPY_SEND_EXIT -DENABLE_NPKIT_EVENT_DIRECT_COPY_SEND_ENTRY -DENABLE_NPKIT_EVENT_DIRECT_COPY_SEND_EXIT -DENABLE_NPKIT_EVENT_DIRECT_RECV_ENTRY -DENABLE_NPKIT_EVENT_DIRECT_RECV_EXIT -DENABLE_NPKIT_EVENT_DIRECT_RECV_COPY_SEND_ENTRY -DENABLE_NPKIT_EVENT_DIRECT_RECV_COPY_SEND_EXIT -DENABLE_NPKIT_EVENT_DIRECT_RECV_REDUCE_COPY_SEND_ENTRY -DENABLE_NPKIT_EVENT_DIRECT_RECV_REDUCE_COPY_SEND_EXIT -DENABLE_NPKIT_EVENT_DIRECT_SEND_ENTRY -DENABLE_NPKIT_EVENT_DIRECT_SEND_EXIT -DENABLE_NPKIT_EVENT_DIRECT_SEND_FROM_OUTPUT_ENTRY -DENABLE_NPKIT_EVENT_DIRECT_SEND_FROM_OUTPUT_EXIT -DENABLE_NPKIT_EVENT_RECV_ENTRY -DENABLE_NPKIT_EVENT_RECV_EXIT -DENABLE_NPKIT_EVENT_RECV_COPY_SEND_ENTRY -DENABLE_NPKIT_EVENT_RECV_COPY_SEND_EXIT -DENABLE_NPKIT_EVENT_RECV_REDUCE_COPY_ENTRY -DENABLE_NPKIT_EVENT_RECV_REDUCE_COPY_EXIT -DENABLE_NPKIT_EVENT_RECV_REDUCE_COPY_SEND_ENTRY -DENABLE_NPKIT_EVENT_RECV_REDUCE_COPY_SEND_EXIT -DENABLE_NPKIT_EVENT_RECV_REDUCE_SEND_ENTRY -DENABLE_NPKIT_EVENT_RECV_REDUCE_SEND_EXIT -DENABLE_NPKIT_EVENT_SEND_ENTRY -DENABLE_NPKIT_EVENT_SEND_EXIT -DENABLE_NPKIT_EVENT_SEND_FROM_OUTPUT_ENTRY -DENABLE_NPKIT_EVENT_SEND_FROM_OUTPUT_EXIT -DENABLE_NPKIT_EVENT_PRIM_SIMPLE_WAIT_PEER_ENTRY -DENABLE_NPKIT_EVENT_PRIM_SIMPLE_WAIT_PEER_EXIT -DENABLE_NPKIT_EVENT_PRIM_SIMPLE_REDUCE_OR_COPY_MULTI_ENTRY -DENABLE_NPKIT_EVENT_PRIM_SIMPLE_REDUCE_OR_COPY_MULTI_EXIT -DENABLE_NPKIT_EVENT_PRIM_LL_WAIT_SEND_ENTRY -DENABLE_NPKIT_EVENT_PRIM_LL_WAIT_SEND_EXIT -DENABLE_NPKIT_EVENT_PRIM_LL_DATA_PROCESS_ENTRY -DENABLE_NPKIT_EVENT_PRIM_LL_DATA_PROCESS_EXIT -DENABLE_NPKIT_EVENT_PRIM_LL128_WAIT_SEND_ENTRY -DENABLE_NPKIT_EVENT_PRIM_LL128_WAIT_SEND_EXIT -DENABLE_NPKIT_EVENT_PRIM_LL128_DATA_PROCESS_ENTRY -DENABLE_NPKIT_EVENT_PRIM_LL128_DATA_PROCESS_EXIT -DENABLE_NPKIT_EVENT_NET_SEND_ENTRY -DENABLE_NPKIT_EVENT_NET_SEND_EXIT -DENABLE_NPKIT_EVENT_NET_RECV_ENTRY -DENABLE_NPKIT_EVENT_NET_RECV_EXIT -DENABLE_NPKIT_EVENT_TIME_SYNC_GPU -DENABLE_NPKIT_EVENT_TIME_SYNC_CPU -DENABLE_NPKIT_EVENT_ALL_REDUCE_RING_SEND_ENTRY -DENABLE_NPKIT_EVENT_ALL_REDUCE_RING_SEND_EXIT -DENABLE_NPKIT_EVENT_ALL_REDUCE_RING_RECV_REDUCE_SEND_ENTRY -DENABLE_NPKIT_EVENT_ALL_REDUCE_RING_RECV_REDUCE_SEND_EXIT -DENABLE_NPKIT_EVENT_ALL_REDUCE_RING_DIRECT_RECV_REDUCE_COPY_SEND_ENTRY -DENABLE_NPKIT_EVENT_ALL_REDUCE_RING_DIRECT_RECV_REDUCE_COPY_SEND_EXIT -DENABLE_NPKIT_EVENT_ALL_REDUCE_RING_DIRECT_RECV_COPY_SEND_ENTRY -DENABLE_NPKIT_EVENT_ALL_REDUCE_RING_DIRECT_RECV_COPY_SEND_EXIT -DENABLE_NPKIT_EVENT_ALL_REDUCE_RING_DIRECT_RECV_ENTRY -DENABLE_NPKIT_EVENT_ALL_REDUCE_RING_DIRECT_RECV_EXIT -DENABLE_NPKIT_EVENT_ALL_REDUCE_TREE_UPDOWN_REDUCE_ENTRY -DENABLE_NPKIT_EVENT_ALL_REDUCE_TREE_UPDOWN_REDUCE_EXIT -DENABLE_NPKIT_EVENT_ALL_REDUCE_TREE_UPDOWN_BROADCAST_ENTRY -DENABLE_NPKIT_EVENT_ALL_REDUCE_TREE_UPDOWN_BROADCAST_EXIT -DENABLE_NPKIT_EVENT_ALL_REDUCE_TREE_SPLIT_REDUCE_BROADCAST_ENTRY -DENABLE_NPKIT_EVENT_ALL_REDUCE_TREE_SPLIT_REDUCE_BROADCAST_EXIT -DENABLE_NPKIT_EVENT_ALL_REDUCE_TREE_SPLIT_REDUCE_ENTRY -DENABLE_NPKIT_EVENT_ALL_REDUCE_TREE_SPLIT_REDUCE_EXIT -DENABLE_NPKIT_EVENT_ALL_REDUCE_TREE_SPLIT_BROADCAST_ENTRY -DENABLE_NPKIT_EVENT_ALL_REDUCE_TREE_SPLIT_BROADCAST_EXIT -DENABLE_NPKIT_EVENT_SEND_RECV_LOCAL_COPY_ENTRY -DENABLE_NPKIT_EVENT_SEND_RECV_LOCAL_COPY_EXIT -DENABLE_NPKIT_EVENT_SEND_RECV_SEND_ENTRY -DENABLE_NPKIT_EVENT_SEND_RECV_SEND_EXIT -DENABLE_NPKIT_EVENT_SEND_RECV_RECV_ENTRY -DENABLE_NPKIT_EVENT_SEND_RECV_RECV_EXIT -DENABLE_NPKIT_PRIM_COLLECT_DATA_PROCESS_TIME -DENABLE_NPKIT_EVENT_MSCCL_GENERIC_OP_ENTRY -DENABLE_NPKIT_EVENT_MSCCL_GENERIC_OP_EXIT -DENABLE_NPKIT_EVENT_MSCCL_REDUCE_ENTRY -DENABLE_NPKIT_EVENT_MSCCL_REDUCE_EXIT"
# NPKIT_FLAGS_GPU_PREFIX="-DENABLE_NPKIT -DENABLE_NPKIT_EVENT_TIME_SYNC_CPU -DENABLE_NPKIT_EVENT_TIME_SYNC_GPU -DENABLE_NPKIT_EVENT_COPY_SEND_ENTRY -DENABLE_NPKIT_EVENT_COPY_SEND_EXIT -DENABLE_NPKIT_EVENT_DIRECT_COPY_SEND_ENTRY -DENABLE_NPKIT_EVENT_DIRECT_COPY_SEND_EXIT -DENABLE_NPKIT_EVENT_DIRECT_RECV_ENTRY -DENABLE_NPKIT_EVENT_DIRECT_RECV_EXIT -DENABLE_NPKIT_EVENT_DIRECT_RECV_COPY_SEND_ENTRY -DENABLE_NPKIT_EVENT_DIRECT_RECV_COPY_SEND_EXIT -DENABLE_NPKIT_EVENT_DIRECT_RECV_REDUCE_COPY_SEND_ENTRY -DENABLE_NPKIT_EVENT_DIRECT_RECV_REDUCE_COPY_SEND_EXIT -DENABLE_NPKIT_EVENT_DIRECT_SEND_ENTRY -DENABLE_NPKIT_EVENT_DIRECT_SEND_EXIT -DENABLE_NPKIT_EVENT_DIRECT_SEND_FROM_OUTPUT_ENTRY -DENABLE_NPKIT_EVENT_DIRECT_SEND_FROM_OUTPUT_EXIT -DENABLE_NPKIT_EVENT_RECV_ENTRY -DENABLE_NPKIT_EVENT_RECV_EXIT -DENABLE_NPKIT_EVENT_RECV_COPY_SEND_EXIT -DENABLE_NPKIT_EVENT_RECV_REDUCE_COPY_ENTRY -DENABLE_NPKIT_EVENT_RECV_REDUCE_COPY_EXIT -DENABLE_NPKIT_EVENT_RECV_REDUCE_COPY_SEND_ENTRY -DENABLE_NPKIT_EVENT_RECV_REDUCE_COPY_SEND_EXIT -DENABLE_NPKIT_EVENT_RECV_REDUCE_SEND_ENTRY -DENABLE_NPKIT_EVENT_RECV_REDUCE_SEND_EXIT -DENABLE_NPKIT_EVENT_SEND_ENTRY -DENABLE_NPKIT_EVENT_SEND_EXIT -DENABLE_NPKIT_EVENT_SEND_FROM_OUTPUT_ENTRY -DENABLE_NPKIT_EVENT_SEND_FROM_OUTPUT_EXIT"
export NPKIT_FLAGS=${NPKIT_FLAGS_GPU_PREFIX}
export CPATH=$MAIN_DIR/nccl/build/include:$CPATH          # 头文件路径
# # make
cd $MAIN_DIR/nccl && make -j src.build NPKIT_FLAGS="${NPKIT_FLAGS}" NVCC_GENCODE="-gencode=arch=compute_80,code=sm_80"
cd $MAIN_DIR/nccl-tests && make clean && make -j MPI=1 MPI_HOME=/usr/lib/x86_64-linux-gnu/openmpi NPKIT_FLAGS="${NPKIT_FLAGS}" CUDA_HOME=/usr/local/cuda NCCL_HOME=$MAIN_DIR/nccl/build/

# env
export NCCL_DEBUG_FILE=/dev/stderr
export LD_PRELOAD=$MAIN_DIR/nccl/build/lib/libnccl.so
export LD_LIBRARY_PATH=$MAIN_DIR/nccl/build/lib
# export NCCL_DEBUG=INFO
# export CUDA_VISIBLE_DEVICES=0,1,2,3
export PATH=$PATH:$MAIN_DIR/arnold/arnold_entrypoint/tools/
mkdir -p $MAIN_DIR/npkit/dump
export NPKIT_DUMP_DIR=$MAIN_DIR/npkit/dump


# export NCCL_SOCKET_IFNAME=eno2np1
# export NCCL_DEBUG=INFO
# export PATH="/usr/local/cuda-12.4/bin/:$PATH"

TARGET_DIR="$MAIN_DIR/TestXml_ring/"

# 查找所有.txt文件并逐一重命名
find "$TARGET_DIR" -type f -name "*.txt" | while read file; do
  # 获取文件名及路径
  new_file="${file%.txt}.xml"

  # 重命名文件
  mv "$file" "$new_file"
done

# echo "================== ring =================="
# for ((j=0;j<1;j++)) do
#     echo "===== Round $j ====="
#     ARGS=${*:-"-b 1M -e 2M -f 2"}
#     NCCL_ALGO=ring NCCL_PROTO=Simple mpirun -N 4 $MAIN_DIR/nccl-tests/build/all_gather_perf $ARGS -g 1 -n 2
#     echo "===== Done $j ====="
#     # if [[ $ARNOLD_ID != "0" ]]; then
#     #     echo Worker 0 finished? wait
#     #     sleep 1d
#     #     exit
#     # fi
# done

# echo "================== neogen ring 8*2 =================="
for ((j=0;j<1;j++)) do
    echo "===== Round $j ====="
    NPKIT_DUMP_DIR=$NPKIT_DUMP_DIR \
    NCCL_PROTO=Simple \
    LD_LIBRARY_PATH=$MAIN_DIR/nccl/build/lib:$LD_LIBRARY_PATH \
    NCCL_DEBUG=warn \
    mpirun -N 4 \
    -x LD_LIBRARY_PATH=$MAIN_DIR/nccl/build/lib:$LD_LIBRARY_PATH \
    -x NCCL_PROTO=Simple \
    $MAIN_DIR/nccl-tests/build/gather_perf \
    -b 1M -e 1G -f 2 -g 1 -c 1 -n 1 -w 5 -G 0 -z 0 || true
    # nsys profile --trace=cuda,nvtx,osrt --capture-range=nvtx --output=profile_report_ring4 \
    # --tag-output \
    # MSCCL_ALGO_DIR=$MAIN_DIR/TestXml_ring/Neogen_AG/4GPUs/ring4_1 \
    # NCCL_P2P_LEVEL=SYS \
    echo "===== Done $j ====="
    # if [[ $ARNOLD_ID != "0" ]]; then
    #     echo Worker 0 finished? wait
    #     sleep 1d
    #     exit
    # fi
done

# echo "================== neogen ring 8*2 =================="
# for ((j=0;j<1;j++)) do
#     echo "===== Round $j ====="
#     NPKIT_DUMP_DIR=$NPKIT_DUMP_DIR \
#     NCCL_ALGO=MSCCL \
#     NCCL_PROTO=Simple \
#     MSCCL_ALGO_DIR=$MAIN_DIR/TestXml_ring/Neogen_AG/8GPUs/ring8_1 \
#     # LD_LIBRARY_PATH=$MAIN_DIR/msccl/build/lib:$LD_LIBRARY_PATH \
#     NCCL_DEBUG=info \
#     mpirun -N 4 \
#     --mca btl_tcp_if_include eno2np1 \
#     --mca btl_tcp_port_min_v4 17213 --mca btl_tcp_port_range_v4 1000 \
#     -H 192.168.16.116:4,192.168.16.115:4\
#     -x LD_LIBRARY_PATH=/home/czy/nccl/msccl/build/lib:$LD_LIBRARY_PATH \
#     -x NCCL_ALGO=NVLS \
#     -x CUDA_VISIBLE_DEVICES="0,1,2,3"\
#     $MAIN_DIR/nccl-tests/build/all_gather_perf \
#     -b 1M -e 2M -f 2 -g 1 -c 1 -n 1 -w 5 -G 0 -z 0 || true
    
#     #     --mca btl_tcp_if_include eno2np1 \
#     # --tag-output \
#     # MSCCL_ALGO_DIR=$MAIN_DIR/TestXml_ring/Neogen_AG/4GPUs/ring4_1 \
#     # NCCL_P2P_LEVEL=SYS \
#     echo "===== Done $j ====="
#     # if [[ $ARNOLD_ID != "0" ]]; then
#     #     echo Worker 0 finished? wait
#     #     sleep 1d
#     #     exit
#     # fi
# done

echo "========generate npkit json trace==============="

cd $MAIN_DIR/npkit/NPKit/msccl_samples/

mkdir -p $MAIN_DIR/npkit/results/

python3 npkit_trace_generator.py --npkit_dump_dir=$NPKIT_DUMP_DIR --npkit_event_header_path=$MAIN_DIR/msccl/src/include/npkit/npkit_event.h --output_dir=$MAIN_DIR/npkit/results/

cd $MAIN_DIR/npkit/results/

echo "========DONE==============="

# echo "================== neogen ring 16*1 =================="
# for ((j=0;j<1;j++)) do
#     echo "===== Round $j ====="
#     MPIRUN \
#     -x NCCL_ALGO=MSCCL -x NCCL_PROTO=SIMPLE \
#     -x MSCCL_ALGO_DIR=$MAIN_DIR/TestXml_ring/Neogen_AG/16GPUs/ring16_1 -x NCCL_P2P_LEVEL=SYS \
#     -x LD_LIBRARY_PATH=$MAIN_DIR/msccl/build/lib:$LD_LIBRARY_PATH \
#     --tag-output -x NCCL_DEBUG=warn \
#     $MAIN_DIR/nccl-tests/build/all_gather_perf \
#     -b 1M -e 1024M -f 2 -g 1 -c 1 -n 10 -w 10 -G 10 -z 0 || true
#     echo "===== Done $j ====="
#     if [[ $ARNOLD_ID != "0" ]]; then
#         echo Worker 0 finished? wait
#         sleep 1d
#         exit
#     fi
# done

MPIRUN /usr/bin/pkill -9 "$THIS_FILE" || true